name: Deployment

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        required: true
        options:
        - Shareable Asset
        - Liberty

jobs:
  print:
    name: Deploying branch '${{ github.ref_name }}' for ${{ github.event.inputs.platform }}
    runs-on: ubuntu-latest
    steps:
    - run: echo Deploying branch '${{ github.ref_name }}' for ${{ github.event.inputs.platform }}

  check:
    needs: print
    name: Check Deploy Environment
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ steps.check-deploy-environment.outputs.environment }}
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - id: check-deploy-environment
      run: |
        if [[ "${{ steps.branch-name.outputs.current_branch }}" =~ ^feature/.* ]]
        then
          echo "::set-output name=environment::develop"
        elif [[ "${{ steps.branch-name.outputs.current_branch }}" == 'develop' ]]
        then
          echo "::set-output name=environment::develop"
        elif [[ "${{ steps.branch-name.outputs.current_branch }}" =~ ^release/.* ]]
        then
          echo "::set-output name=environment::staging"
        elif [[ "${{ steps.branch-name.outputs.current_branch }}" == 'main' ]]
        then
          echo "::set-output name=environment::production"
        else
          echo "::set-output name=environment::none"
        fi

  build:
    needs: check
    name: Building branch '${{ github.ref_name }}'
    runs-on: ubuntu-latest
    if: needs.check.outputs.deploy-environment != 'none'

    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Building branch ${{ steps.branch-name.outputs.current_branch }}
      run: |
        echo "Building branch ${{ steps.branch-name.outputs.current_branch }}"


  deploy-nonprod:
    needs: build
    name: Deploy to ${{ needs.check.outputs.deploy-environment }}
    runs-on: ubuntu-latest
    if: needs.check.outputs.deploy-environment != 'none' && needs.check.outputs.deploy-environment != 'production'

    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Deploying branch ${{ steps.branch-name.outputs.current_branch }} to ${{ needs.check.outputs.deploy-environment }}
      run: |
        echo "Deploying branch ${{ steps.branch-name.outputs.current_branch }} to ${{ needs.check.outputs.deploy-environment }}"


  deploy-prod:
    needs: build
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: needs.check.outputs.deploy-environment == 'production'
    environment: production

    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Deploying branch ${{ steps.branch-name.outputs.current_branch }} to ${{ needs.check.outputs.deploy-environment }}
      run: |
        echo "Deploying branch ${{ steps.branch-name.outputs.current_branch }} to ${{ needs.check.outputs.deploy-environment }}"
